// import { Inter } from "next/font/google";
import Footer from "@/components/Footer/footer";
import Header from "@/components/Header/header";
import SocialHeader from "@/components/Header/SocialHeader";
import Breadcrumbs from "@/components/Breadcrumbs/breadcrumbs";
import "@/styles/header.scss";
import "@/styles/SocialHeader.scss";
import "@/styles/footer.scss";
import "@/styles/breadcrumb.scss";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
            <SocialHeader />
            <Header />
            <Breadcrumbs />
              {children}
            <Footer />
      </body>
    </html>
  );
}
