// import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Providers from "@/utils/Providers";
import SessionProvider from "@/utils/SessionProvider";
import { ReactQueryClientProvider } from "@/utils/providers/ReactQueryProvider";
import "@/styles/bootstrap.css";
import "@/styles/pe-icon-7-stroke.css";
import "@/styles/font-awesome.css";
import "@/styles/global.scss";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch session data on the server side
  const session = await getServerSession();

  // Extract the session data as a plain object
  const sessionData = session ? { user: session.user } : null;
  return (
    <html lang="en">
      <body >
        <ReactQueryClientProvider>
          <SessionProvider session={sessionData}>
            <Providers>
              {children}
            </Providers>
          </SessionProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
